export const SET_RECIPES = "SET_RECIPES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES"
export const DELETE_RECIPE_FROM_FAVORITES = "DELETE_RECIPE_FROM_FAVORITES"


export const LOGOUT_USER = "LOGOUT_USER"
export const ADD_USER_TO_STATE = "ADD_USER_TO_STATE"